// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlwMAShFmlCzcN9IxaWD4dkfDXp0fU6U',
    appId: '1:960319770148:web:b6ef1a7d87a1a0908e92b1',
    messagingSenderId: '960319770148',
    projectId: 'talkwith-m',
    authDomain: 'talkwith-m.firebaseapp.com',
    storageBucket: 'talkwith-m.firebasestorage.app',
    measurementId: 'G-6R253LYQG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2GKpN-QBC9s-dQYA_eRrYe3I4hx0oGUE',
    appId: '1:960319770148:android:413327029873efb68e92b1',
    messagingSenderId: '960319770148',
    projectId: 'talkwith-m',
    storageBucket: 'talkwith-m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKhS486VnFRQ757nmL84C3YC6ixLcWKaQ',
    appId: '1:960319770148:ios:e432a5637bfe1aa58e92b1',
    messagingSenderId: '960319770148',
    projectId: 'talkwith-m',
    storageBucket: 'talkwith-m.firebasestorage.app',
    androidClientId:
        '960319770148-34tjcoh1hropsclrjncqbvul64g4l37l.apps.googleusercontent.com',
    iosClientId:
        '960319770148-8hal0c4e14mh0kfqbgf5lcannipb9v3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkShow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKhS486VnFRQ757nmL84C3YC6ixLcWKaQ',
    appId: '1:960319770148:ios:e432a5637bfe1aa58e92b1',
    messagingSenderId: '960319770148',
    projectId: 'talkwith-m',
    storageBucket: 'talkwith-m.firebasestorage.app',
    androidClientId:
        '960319770148-34tjcoh1hropsclrjncqbvul64g4l37l.apps.googleusercontent.com',
    iosClientId:
        '960319770148-8hal0c4e14mh0kfqbgf5lcannipb9v3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkShow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDlwMAShFmlCzcN9IxaWD4dkfDXp0fU6U',
    appId: '1:960319770148:web:14b96d1417fef9a78e92b1',
    messagingSenderId: '960319770148',
    projectId: 'talkwith-m',
    authDomain: 'talkwith-m.firebaseapp.com',
    storageBucket: 'talkwith-m.firebasestorage.app',
    measurementId: 'G-WQ40T5CZL6',
  );
}
